config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :values
  resources :themes
  resources :images
  resources :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    match 'next_image',       to: 'api#next_image',   via: :get
    match 'prev_image',       to: 'api#prev_image',   via: :get
    match 'save_value',       to: 'api#save_value',   via: :get
  end

  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'

  match 'work', to: 'work#index',via: 'get'
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme', to: 'work#choose_theme', via: :get
  match 'display_theme', to: 'work#display_theme', via: :post, as: :js

  match 'results_list',     to: 'work#results_list', via: :get

  match 'save_value',       to: 'api/api#save_value',   via: :get

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'

  root 'main#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :values, dependent: :destroy
  before_save { self.email = email.downcase }
  # before_save { email.downcase! } # alternative
  before_create :create_remember_token

  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }
  # validates :email, presence: true, uniqueness: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, length: { minimum: 6 }

  def self.all_cached
    # ids = Rails.cache.fetch('User.all') do
    #   User.all.pluck(:id)
    # end
    # User.find(ids)

    Rails.cache.fetch('User.all') { all }
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating">
    <%= form.text_field :name, class:"form-control",placeholder:"login"%>
    <%= form.label t('.name')%>
  </div>

  <div class="form-floating">
    <%= form.text_field :email,class:"form-control",placeholder:"name@example.com" %>
    <%= form.label "Email" %>
  </div>
  <div class="form-floating">
    <%= form.password_field :password,class:"form-control",placeholder:"*****"%>
    <%= form.label t('.password')%>

  </div>
  <div class="form-floating">
    <%= form.password_field :password_confirmation,class:"form-control",placeholder:"*****" %>
    <%= form.label t('.password_confirmation') %>
  </div>

  <div class="actions">
    <%= form.submit t(".create_account"), class:"w-100 btn btn-large btn-primary mt-3" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t(".edit_user") %></h1>

<%= render 'form', user: @user %>

<%= link_to t("users.show.show"), @user, class:"w-100 mt-3 btn btn-success" %>
<%= link_to t("users.new.back"), users_path, class:"w-100 mt-3 btn btn-secondary" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t(".users") %></h1>
<table>
  <thead>
    <tr>
      <th><%= t("users.form.name") %></th>
      <th><%= t("users.show.email") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to t("users.show.show"), user %></td>
        <td><%= link_to t("users.show.edit"), edit_user_path(user) %></td>
        <td><%= link_to t("users.show.destroy"), user, method: :delete, data: { confirm: t(".confirm") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t(".new_user"), new_user_path %>

app/views/users/new.html.erb
<h1 class="mb-3 fw-normal"><%= t(".new_user_sign_up")%></h1>

<%= render 'form', user: @user %>

<%= link_to t(".back"), users_path, class:"w-100 mt-3 btn btn-secondary" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show_user">
  <div class="row">
    <aside class="span4">
      <section>
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
  </div>
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <%= link_to t(".work"), work_path, class: "w-100 mt-3 btn btn-primary" %>
</div>

<%= link_to t("users.show.edit"), edit_user_path(@user), class:"w-100 mt-3 btn btn-warning" %>
<%= link_to t("users.new.back"), users_path, class:"w-100 mt-3 btn btn-secondary" %>