config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :values
  resources :themes
  resources :images
  resources :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    match 'next_image',       to: 'api#next_image',   via: :get
    match 'prev_image',       to: 'api#prev_image',   via: :get
    match 'save_value',       to: 'api#save_value',   via: :get
  end

  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'

  match 'work', to: 'work#index',via: 'get'
  match 'choose_image',     to: 'work#choose_image',      via: :get
  match 'choose_theme', to: 'work#choose_theme', via: :get
  match 'display_theme', to: 'work#display_theme', via: :post, as: :js

  match 'results_list',     to: 'work#results_list', via: :get

  match 'save_value',       to: 'api/api#save_value',   via: :get

  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'delete'

  root 'main#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p>
      <%= t(".website_by") %> <a href="https://github.com/DGSR/ruby-workout"><%= t(".author")%></a>, 2021.
    </p>
    <p class="locale">
      <%= link_to image_tag("Russia.jpg", alt:"", style: "width: 5%; height: 5%", title: "Русский"),locale: :ru %>
      <%= link_to image_tag("United_Kingdom.jpg", alt:"", style: "width: 6%; height: 6%", title: "English"),locale: :en %>
      <b>
        <%= I18n.locale %>
      </b>
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Resemblence</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%=link_to t('.home'), root_path,class:'nav-link active' %>
      <%=link_to t('.help'), main_help_path,class:'nav-link'  %>
      <%=link_to t('.contact'), main_contacts_path,class:'nav-link' %>
      <%=link_to t('.about'), main_about_path,class:'nav-link'  %>
      <% if signed_in? %>
        <%link_to "Users", '#',class:'nav-link' %>
        <div class="dropdown nav-link">
          <%=link_to "#", id: "navbar-dropdown", class: "dropdown-toggle", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
            <%= t('.person') %>
          <% end %>
          <div class="dropdown-menu" aria-labelledby="navbar-dropdown">
              <%= link_to t('.profile'), current_user, class:'dropdown-item' %>
              <%= link_to t('.settings'), '#', class:' dropdown-item'%>
              <%= link_to t('.sign_out'), signout_path, method: "delete", class:'dropdown-item' %>
          </div>
        </div>
        <div class="logged nav-link">
          <%= @current_user.email%>
        </div>
        <%= gravatar_for current_user %>
      <% else %>
          <%= link_to t('.sign_in'), signin_path, class:'nav-link'%>
      <% end %>
    </nav>
  </div>
</header>